# Generated by Django 5.1.2 on 2024-10-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(default='Generalista', max_length=100),
        ),
        migrations.AddField(
            model_name='medico',
            name='nome',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
