# Generated by Django 5.1.2 on 2024-10-22 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medico_especialidade_medico_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='consulta',
            name='data',
            field=models.DateField(default=datetime.date(2024, 10, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(default=datetime.time(3, 4, 39, 875771)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
