# Generated by Django 5.1.2 on 2024-10-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_medico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
    ]
