# Generated by Django 5.1.2 on 2024-10-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
