# Generated by Django 5.1.2 on 2024-10-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paciente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='cpf',
        ),
    ]
